apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: test-avishay
        url: https://34.28.174.107
      - cluster: test-marina
        url: https://34.75.213.247
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/marina-vrublevsky/test-repo.git
        targetRevision: main
        path: guestbook
      destination:
        server: '{{url}}'
        namespace: default