apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: guestbook
        ports:
        - containerPort: 80
        resources:
            requests:
                cpu: 500m
                memory: 0.5Gi
            limits:
                cpu: 1
                memory: 1Gi
